# This is the config file for building RasterClass with Travis-ci.org
services:
  - mongodb
matrix:
  fast_finish: true
  include:
    - osx_image: xcode8.2
      language: cpp
      compiler: clang
      sudo: required
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=osx_xcode
        - DETAILS="debug build, libtool"
        - ENABLE_CXX11=1
        
before_install:
  - ./ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./ci/travis/${BUILD_NAME}/install.sh

script:
  - ./ci/travis/${BUILD_NAME}/script.sh

notifications:
  email:false
