version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2013
configuration: Release
platform: x64
services: mongodb
build:
  verbosity: minimal
environment:
  global:
    GDAL_HOME: "C:\\gdal"
install:
  # download compiled gdal and install it
  - ps: mkdir C:\gdal | out-null
  - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3.zip --output gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3-libs.zip --output gdallibs.zip  
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET PATH=C:\\GDAL\\bin\\ms\\apps;C:\\GDAL\\bin\\curl;C:\\GDAL\\bin\\proj\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"
  - "SET GDAL_DIR=C:\\gdal"
  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""
  # compile mongo-c-driver
  - appveyor DownloadFile https://github.com/mongodb/mongo-c-driver/archive/1.6.1.zip -FileName mongo-c-driver.zip
  - 7z x mongo-c-driver.zip -oC:\
  - cd C:\mongo-c-driver-1.6.1
  - ps: "ls"
  - cd src\libbson
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - cd ..\..
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -DBSON_ROOT_DIR=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - "SET MONGOC_ROOT_DIR=C:\\mongo-c-driver"
  - "SET MONGOC_LIB_DIR=C:\\mongo-c-driver\\bin"
  - "SET PATH=C:\\mongo-c-driver\\bin;%PATH%"
build_script:
  - cd C:\projects\rasterclass
  - ps: "ls"
  - mkdir build
  - cmake -G "Visual Studio 12 2013 Win64" .. -DCMAKE_BUILD_TYPE=Release
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
test_script:
  - ps: "ls"
  - ./bin/RasterClass