version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2010
configuration: Release
platform: x64
services: mongodb
build:
  verbosity: minimal
environment:
  global:
    GDAL_HOME: "C:\\gdal"
install:
  - curl http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-4-mapserver-6-4-3.zip --output gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - curl http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-4-mapserver-6-4-3-libs.zip --output gdallibs.zip  
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"

  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""